openapi: 3.0.0

servers:
  - description: Local
    url: http://localhost:8000/admin-api/v1

info:
  description: Admin api documentation
  version: "1.0.0"
  title: Admin
  contact:
    email: mdaejje123@gmail.com
tags:
  - name: auth
    description: Auth
  - name: cars
    description: Cars
  - name: option
    description: Option
  - name: configuration
    description: Configuration
  - name: configuration-options
    description: Configuration option
  - name: price
    description: Price

paths:
  /auth/login:
    post:
      tags:
        - auth
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                code:
                  type: string
                password:
                  type: string
              required:
                - email
      responses:
        '422':
          $ref: '#/components/responses/Error422'
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /cars:
    get:
      tags:
        - cars
      operationId: fetchCars
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Paginated'
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/Car'
    post:
      tags:
        - cars
      operationId: createCar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      responses:
        '422':
          $ref: '#/components/responses/Error422'
        '200':
          $ref: '#/components/responses/Success'

  /cars/{id}:
    put:
      tags:
        - cars
      operationId: updateCar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      responses:
        '422':
          $ref: '#/components/responses/Error422'
        '200':
          $ref: '#/components/responses/Success'
    delete:
      tags:
        - cars
      operationId: deleteCar
      responses:
        '422':
          $ref: '#/components/responses/Error422'
        '200':
          $ref: '#/components/responses/Success'

  /options:
    get:
      tags:
        - option
      operationId: fetchOptions
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Paginated'
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/Option'
    post:
      tags:
        - option
      operationId: createOption
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      responses:
        '422':
          $ref: '#/components/responses/Error422'
        '200':
          $ref: '#/components/responses/Success'

  /options/{id}:
    put:
      tags:
        - option
      operationId: updateOption
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      responses:
        '422':
          $ref: '#/components/responses/Error422'
        '200':
          $ref: '#/components/responses/Success'
    delete:
      tags:
        - option
      operationId: deleteOption
      responses:
        '422':
          $ref: '#/components/responses/Error422'
        '200':
          $ref: '#/components/responses/Success'

  /configurations/fetch-meta:
    get:
      tags:
        - configuration
      operationId: fetchMeta
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  cars:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string

  /configurations:
    get:
      tags:
        - configuration
      operationId: fetchConfigurations
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Paginated'
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/Configuration'
    post:
      tags:
        - configuration
      operationId: createConfiguration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                car_id:
                  type: integer
                name:
                  type: string
              required:
                - car_id
                - name
      responses:
        '422':
          $ref: '#/components/responses/Error422'
        '200':
          $ref: '#/components/responses/Success'

  /configurations/{id}:
    put:
      tags:
        - configuration
      operationId: updateConfiguration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                car_id:
                  type: integer
                name:
                  type: string
              required:
                - car_id
                - name
      responses:
        '422':
          $ref: '#/components/responses/Error422'
        '200':
          $ref: '#/components/responses/Success'
    delete:
      tags:
        - configuration
      operationId: deleteConfiguration
      responses:
        '422':
          $ref: '#/components/responses/Error422'
        '200':
          $ref: '#/components/responses/Success'

  /configuration-options/fetch-meta:
    get:
      tags:
        - configuration-options
      operationId: fetchMeta
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  configurations:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                  options:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string

  /configuration-options:
    get:
      tags:
        - configuration-options
      operationId: fetchConfigurationOptions
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Paginated'
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/ConfigurationOption'
    post:
      tags:
        - configuration-options
      operationId: createConfigurationOption
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                configuration_id:
                  type: integer
                option_id:
                  type: string
              required:
                - configuration_id
                - option_id
      responses:
        '422':
          $ref: '#/components/responses/Error422'
        '200':
          $ref: '#/components/responses/Success'

  /configuration-options/{id}:
    put:
      tags:
        - configuration-options
      operationId: updateConfigurationOption
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                configuration_id:
                  type: integer
                option_id:
                  type: string
              required:
                - configuration_id
                - option_id
      responses:
        '422':
          $ref: '#/components/responses/Error422'
        '200':
          $ref: '#/components/responses/Success'
    delete:
      tags:
        - configuration-options
      operationId: deleteConfigurationOption
      responses:
        '422':
          $ref: '#/components/responses/Error422'
        '200':
          $ref: '#/components/responses/Success'

  /prices/fetch-meta:
    get:
      tags:
        - price
      operationId: fetchMeta
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  configurations:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
  /prices:
    get:
      tags:
        - price
      operationId: fetchPrices
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Paginated'
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/Price'
    post:
      tags:
        - price
      operationId: createPrice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                configuration_id:
                  type: integer
                price:
                  type: integer
                start_date:
                  type: string
                end_date:
                  type: string
              required:
                - configuration_id
                - price
                - start_Date
                - end_Date
      responses:
        '422':
          $ref: '#/components/responses/Error422'
        '200':
          $ref: '#/components/responses/Success'

  /prices/{id}:
    put:
      tags:
        - price
      operationId: updatePrice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                configuration_id:
                  type: integer
                price:
                  type: integer
                start_date:
                  type: string
                end_date:
                  type: string
              required:
                - configuration_id
                - price
                - start_Date
                - end_Date
      responses:
        '422':
          $ref: '#/components/responses/Error422'
        '200':
          $ref: '#/components/responses/Success'
    delete:
      tags:
        - price
      operationId: deletePrice
      responses:
        '422':
          $ref: '#/components/responses/Error422'
        '200':
          $ref: '#/components/responses/Success'

components:
  responses:
    Success:
      description: Success
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Success'

    Error422:
      description: Validation failure
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error422'

  schemas:
    Success:
      type: object
      properties:
        status:
          type: boolean
        message:
          type: string

    Error422:
      type: object
      properties:
        message:
          type: string
        errors:
          type: object

    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        gate:
          type: string

    Paginated:
      type: object
      properties:
        current_page:
          type: integer
        first_page_url:
          type: string
        from:
          type: integer
        last_page:
          type: integer
        last_page_url:
          type: string
        links:
          type: array
          items:
            properties:
              url:
                type: string
                nullable: true
              label:
                type: string
              active:
                type: boolean
        next_page_url:
          type: string
        path:
          type: string
        per_page:
          type: integer
        prev_page_url:
          type: string
        to:
          type: integer
        total:
          type: integer

    Car:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        updated_at:
          type: string
        created_at:
          type: string

    Option:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        updated_at:
          type: string
        created_at:
          type: string

    Configuration:
      type: object
      properties:
        id:
          type: integer
        car_id:
          type: integer
        name:
          type: string
        updated_at:
          type: string
        created_at:
          type: string

    ConfigurationOption:
      type: object
      properties:
        id:
          type: integer
        configuration_id:
          type: integer
        option_id:
          type: integer

    Price:
      type: object
      properties:
        id:
          type: integer
        configuration_id:
          type: integer
        price:
          type: integer
        start_date:
          type: string
        end_date:
          type: string