openapi: 3.0.0

info:
  description: Web api documentation
  version: "1.0.0"
  title: Web
  contact:
    email: mdaejje123@gmail.com
tags:
  - name: cars
    description: 'Cars'

paths:
  /cars/available:
    get:
      tags:
        - cars
      operationId: fetchAvailableCars
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AvailableCar'

components:
  schemas:
    AvailableCar:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          name:
            type: string
          configurations:
            type: array
            items:
              $ref: '#/components/schemas/Configuration'

    Configuration:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        options:
          type: array
          items:
            type: string
        current_price:
          type: integer